// Report export. Builds an HTML statement and turns it into a shareable PDF via
// expo-print + expo-sharing. Both are free and offline.

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { MemberBalance } from '@/types';
import { formatMoney } from '@/logic/money';
import { formatDayLabel } from '@/logic/datetime';
import type { PeriodTotals } from '@/logic/analytics';

interface ReportInput {
  orgName: string;
  periodLabel: string;
  fromISO: string;
  toISO: string;
  totals: PeriodTotals;
  balances: MemberBalance[];
  currency: string;
}

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
}

export function buildReportHtml(input: ReportInput): string {
  const rows = input.balances
    .map(
      (b) => `<tr>
        <td>${esc(b.memberName)}</td>
        <td class="num">${formatMoney(b.totalCharged, input.currency)}</td>
        <td class="num">${formatMoney(b.totalPaid, input.currency)}</td>
        <td class="num ${b.balance > 0 ? 'due' : 'ok'}">${formatMoney(b.balance, input.currency)}</td>
      </tr>`,
    )
    .join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Roboto, sans-serif; color: #1D2433; padding: 24px; }
    h1 { color: #FF5A3C; margin-bottom: 4px; }
    .sub { color: #667085; margin-top: 0; }
    .cards { display: flex; gap: 12px; margin: 20px 0; }
    .card { flex: 1; background: #FFF6F2; border-radius: 12px; padding: 14px; }
    .card .v { font-size: 22px; font-weight: 800; }
    .card .l { color: #667085; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #EAECF0; font-size: 13px; }
    th { color: #667085; text-transform: uppercase; font-size: 11px; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .due { color: #F04438; font-weight: 700; }
    .ok { color: #12B76A; }
    .foot { margin-top: 24px; color: #98A2B3; font-size: 11px; }
  </style></head><body>
    <h1>${esc(input.orgName)}</h1>
    <p class="sub">Tiffin statement · ${esc(input.periodLabel)} (${formatDayLabel(input.fromISO)} – ${formatDayLabel(input.toISO)})</p>
    <div class="cards">
      <div class="card"><div class="v">${input.totals.tiffinCount}</div><div class="l">Tiffins</div></div>
      <div class="card"><div class="v">${formatMoney(input.totals.totalCharged, input.currency)}</div><div class="l">Charged</div></div>
      <div class="card"><div class="v">${formatMoney(input.totals.totalPaid, input.currency)}</div><div class="l">Collected</div></div>
    </div>
    <table>
      <thead><tr><th>Member</th><th class="num">Charged</th><th class="num">Paid</th><th class="num">Balance</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p class="foot">Generated by Tiffin Manager on ${formatDayLabel(new Date().toISOString().slice(0, 10))}.</p>
  </body></html>`;
}

/** Render the report to a PDF file and open the share sheet. */
export async function exportReportPdf(input: ReportInput): Promise<void> {
  const html = buildReportHtml(input);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Tiffin statement' });
  }
}
